# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GPR
                                 A QGIS plugin
 GPR
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-04-23
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Giuseppe
        email                : guarino.archeo@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


# -*- coding: utf-8 -*-
"""
GPR - QGIS Plugin Implementation
"""

from qgis.PyQt.QtCore import QSettings, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from .trace_tools_mixin import TraceToolsMixin
from .trace_info_mixin import TraceInfoMixin
from .trace_capture_mixin import TraceCaptureMixin
from .trace_build3d_mixin import TraceBuild3DMixin
from .catalog_group_mixin import CatalogGroupMixin
from .catalog_tools_mixin import CatalogToolsMixin
from .grid_workflow_mixin import GridWorkflowMixin
from .ui_layout_mixin import UiLayoutMixin
from .app_runtime_mixin import AppRuntimeMixin

from .resources import *
import os.path


class GeoSurveyStudioPlugin(
    AppRuntimeMixin,
    CatalogGroupMixin,
    CatalogToolsMixin,
    GridWorkflowMixin,
    UiLayoutMixin,
    TraceInfoMixin,
    TraceCaptureMixin,
    TraceBuild3DMixin,
    TraceToolsMixin,
):
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor."""
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.actions = []
        self.brand_name = "GeoSurvey Studio"
        self.menu = self.tr(u'&GeoSurvey Studio')
        self.first_start = None
        self.dlg = None
        self.dock_widget = None
        self.settings = QSettings()
        self.settings_group = "GeoSurveyStudio"
        self.settings_key_active_project = "GeoSurveyStudio/active_project_root"
        self.settings_key_default_import_crs = "GeoSurveyStudio/default_import_crs_authid"
        self.grid_use_snap = True
        self.grid_snap_mode = "all"
        self.grid_snap_tolerance = 12.0
        self.grid_snap_units = "pixels"
        self.grid_force_orthogonal = False
        self.grid_relative_orthogonal = False
        self.keep_source_polygon = True
        self.grid_dimension_mode = "ask"
        self.grid_internal_enabled = True
        self.snap_checkbox = None
        self.snap_mode_combo = None
        self.snap_tolerance_spin = None
        self.snap_units_combo = None
        self.ortho_checkbox = None
        self.ortho_base_checkbox = None
        self.keep_area_checkbox = None
        self.dimension_mode_combo = None
        self.help_button = None
        self.export_button = None
        self.base_angle_label = None
        self.length_label = None
        self.orientation_status_label = None
        self.orientation_helper_dialog = None
        self.orientation_helper_status_label = None
        self.orientation_helper_edits = {}
        self._orientation_helper_syncing = False
        self.internal_grid_checkbox = None
        self.name_raster_panel = None
        self.name_raster_title = None
        self.name_raster_lines = []
        self.group_tools_label = None
        self.image_tools_label = None
        self.tools_tabs = None
        self.load_groups_button = None
        self.bottom_controls_widget = None
        self.dialog_main_layout = None
        self.left_nav_widget = None
        self._is_narrow_layout = None
        self.coord_x0_label = None
        self.coord_x1_label = None
        self.coord_y0_label = None
        self.coord_y1_label = None
        self.cell_x_label = None
        self.cell_y_label = None
        self.last_area_layer = None
        self.last_grid_layer = None
        self.pending_vector_storage_mode = None
        self.project_manager_dialog = None
        self.plugin_layer_root_name = "GeoSurvey Studio"
        self.trace_toolbar = None
        self.trace_info_action = None
        self.trace_toolbar_actions = {}
        self.trace_line_layer_id = None
        self.trace_connected_layer_ids = set()
        self.trace_capture_context = None
        self.trace_info_dock = None
        self.trace_info_table = None
        self.trace_info_model = None
        self.trace_info_filter_edit = None
        self.trace_info_filter_field_combo = None
        self.trace_info_mode_combo = None
        self.trace_info_sort_field_combo = None
        self.trace_info_sort_order_combo = None
        self.trace_info_stack = None
        self.trace_info_form_list = None
        self.trace_info_form_fields = {}
        self.trace_info_form_preview_combo = None
        self.trace_info_form_preview_key = "timeslice"
        self.trace_info_view_table_btn = None
        self.trace_info_view_form_btn = None
        self.trace_info_query_btn = None
        self.trace_info_query_panel = None
        self.trace_info_help_btn = None
        self.trace_info_help_panel = None
        self.trace_info_selection_guard = False
        self.trace_info_is_docked = False
        self.trace_info_saved_selected_fid = None
        self.trace_info_saved_selected_trace_id = ""
        self.trace_z_grid_cache = {}
        self.trace_missing_z_prompt_shown = False
        self.trace_allow_missing_z_for_session = False

    # Translation helper
    def tr(self, message):
        return QCoreApplication.translate('GeoSurveyStudio', message)

    # Add actions to the toolbar/menu
    def add_action(self, icon_path, text, callback, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        self.iface.addToolBarIcon(action)
        self.iface.addPluginToMenu(self.menu, action)
        self.actions.append(action)
        return action

    def initGui(self):
        """Initialize the GUI."""
        icon_path = ':/plugins/gpr_linker/icon.png'
        self.add_action(icon_path, text=self.tr(u'GeoSurvey Studio'), callback=self.run, parent=self.iface.mainWindow())
        pm_action = self.add_action(
            icon_path,
            text=self.tr(u'GeoSurvey Studio Project Manager'),
            callback=self.open_project_manager,
            parent=self.iface.mainWindow(),
        )
        pm_icon_path = os.path.join(self.plugin_dir, "icon2.png")
        if os.path.exists(pm_icon_path):
            pm_action.setIcon(QIcon(pm_icon_path))
        self._ensure_trace_actions()
        self.trace_info_action = self.add_action(
            icon_path,
            text=self.tr(u'2D/3D Draw Panel'),
            callback=self.open_trace_info_tab,
            parent=self.iface.mainWindow(),
        )
        pencil_icon = self._qgis_theme_icon("mActionToggleEditing.svg", "mActionAddFeature.svg")
        if pencil_icon is not None and not pencil_icon.isNull():
            self.trace_info_action.setIcon(pencil_icon)
        self.first_start = True

    def unload(self):
        """Unload the plugin."""
        if self.dlg is not None:
            self._save_ui_settings()
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&GeoSurvey Studio'), action)
            self.iface.removeToolBarIcon(action)
        if self.dock_widget is not None:
            self.iface.removeDockWidget(self.dock_widget)
            self.dock_widget.deleteLater()
            self.dock_widget = None
            self.dlg = None
        if self.trace_toolbar is not None:
            try:
                self.iface.mainWindow().removeToolBar(self.trace_toolbar)
            except Exception:
                pass
            self.trace_toolbar.deleteLater()
            self.trace_toolbar = None
            self.trace_toolbar_actions = {}
        if self.trace_info_dock is not None:
            try:
                self.iface.removeDockWidget(self.trace_info_dock)
            except Exception:
                pass
            self.trace_info_dock.deleteLater()
            self.trace_info_dock = None
            self.trace_info_table = None
            self.trace_info_model = None
            self.trace_info_filter_edit = None
            self.trace_info_filter_field_combo = None
            self.trace_info_mode_combo = None
            self.trace_info_sort_field_combo = None
            self.trace_info_sort_order_combo = None
            self.trace_info_stack = None
            self.trace_info_form_list = None
            self.trace_info_form_fields = {}
            self.trace_info_form_preview_combo = None
            self.trace_info_form_preview_key = "timeslice"
            self.trace_info_view_table_btn = None
            self.trace_info_view_form_btn = None
            self.trace_info_query_btn = None
            self.trace_info_query_panel = None
            self.trace_info_help_btn = None
            self.trace_info_help_panel = None
            self.trace_info_selection_guard = False
            self.trace_info_is_docked = False
        if self.orientation_helper_dialog is not None:
            try:
                self.orientation_helper_dialog.hide()
            except Exception:
                pass
            try:
                self.orientation_helper_dialog.deleteLater()
            except Exception:
                pass
            self.orientation_helper_dialog = None
            self.orientation_helper_status_label = None
            self.orientation_helper_edits = {}
            self._orientation_helper_syncing = False
        self.trace_z_grid_cache = {}

