# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geosurvey_studio_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QDialog
from PyQt5.QtCore import Qt
try:
    from .geosurvey_studio_dialog_base import Ui_Dialog
except Exception:
    # Allow direct module import in test environments.
    from geosurvey_studio_dialog_base import Ui_Dialog

class GeoSurveyStudioDialog(QDialog, Ui_Dialog):
    def __init__(self, parent=None):
        super(GeoSurveyStudioDialog, self).__init__(parent)
        self.setupUi(self)
        self.on_resized = None

    def keyPressEvent(self, event):
        # Prevent ESC from closing the plugin panel/dialog.
        if event.key() == Qt.Key_Escape:
            event.accept()
            return
        super(GeoSurveyStudioDialog, self).keyPressEvent(event)

    def resizeEvent(self, event):
        super(GeoSurveyStudioDialog, self).resizeEvent(event)
        if callable(self.on_resized):
            try:
                self.on_resized(event.size())
            except Exception:
                pass
