# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpr_linker_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(794, 521)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 1, 8, 2)
        self.labelSelezionaRaster = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSelezionaRaster.setFont(font)
        self.labelSelezionaRaster.setObjectName("labelSelezionaRaster")
        self.gridLayout_3.addWidget(self.labelSelezionaRaster, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 4, 2, 1)
        self.rasterListWidget = QtWidgets.QListWidget(Dialog)
        self.rasterListWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.rasterListWidget.setObjectName("rasterListWidget")
        self.gridLayout_3.addWidget(self.rasterListWidget, 1, 3, 4, 1)
        self.lebelstep = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lebelstep.setFont(font)
        self.lebelstep.setObjectName("lebelstep")
        self.gridLayout_3.addWidget(self.lebelstep, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 4, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setEnabled(False)
        self.textBrowser.setMouseTracking(False)
        self.textBrowser.setAutoFillBackground(True)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.HLine)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser.setLineWidth(-8)
        self.textBrowser.setMidLineWidth(-5)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 3, 0, 4, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 4, 4, 1, 1)
        self.labelseleziona = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelseleziona.setFont(font)
        self.labelseleziona.setObjectName("labelseleziona")
        self.gridLayout_3.addWidget(self.labelseleziona, 5, 3, 1, 1)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupListWidget = QtWidgets.QListWidget(self.widget)
        self.groupListWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.groupListWidget.setSelectionRectVisible(False)
        self.groupListWidget.setObjectName("groupListWidget")
        self.horizontalLayout_2.addWidget(self.groupListWidget)
        self.gridLayout_3.addWidget(self.widget, 6, 2, 2, 2)
        self.dial = QtWidgets.QDial(Dialog)
        self.dial.setMouseTracking(False)
        self.dial.setTabletTracking(False)
        self.dial.setAcceptDrops(False)
        self.dial.setAutoFillBackground(False)
        self.dial.setProperty("value", 0)
        self.dial.setSliderPosition(0)
        self.dial.setTracking(True)
        self.dial.setOrientation(QtCore.Qt.Horizontal)
        self.dial.setWrapping(False)
        self.dial.setNotchTarget(3.699999999999999)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.gridLayout_3.addWidget(self.dial, 7, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupNameEdit = QtWidgets.QLineEdit(Dialog)
        self.groupNameEdit.setObjectName("groupNameEdit")
        self.gridLayout.addWidget(self.groupNameEdit, 2, 1, 1, 1)
        self.createGroupButton = QtWidgets.QPushButton(Dialog)
        self.createGroupButton.setObjectName("createGroupButton")
        self.gridLayout.addWidget(self.createGroupButton, 2, 0, 1, 1)
        self.openButton = QtWidgets.QDialogButtonBox(Dialog)
        self.openButton.setStandardButtons(QtWidgets.QDialogButtonBox.Open)
        self.openButton.setCenterButtons(True)
        self.openButton.setObjectName("openButton")
        self.gridLayout.addWidget(self.openButton, 4, 0, 1, 1)
        self.Ok = QtWidgets.QDialogButtonBox(Dialog)
        self.Ok.setOrientation(QtCore.Qt.Horizontal)
        self.Ok.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Ok.setObjectName("Ok")
        self.gridLayout.addWidget(self.Ok, 4, 1, 1, 1)
        self.moveRasterButton = QtWidgets.QPushButton(Dialog)
        self.moveRasterButton.setObjectName("moveRasterButton")
        self.gridLayout.addWidget(self.moveRasterButton, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_3.addLayout(self.horizontalLayout, 7, 4, 2, 1)
        self.nomeraster = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.nomeraster.setFont(font)
        self.nomeraster.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nomeraster.setLineWidth(1)
        self.nomeraster.setMidLineWidth(0)
        self.nomeraster.setScaledContents(False)
        self.nomeraster.setObjectName("nomeraster")
        self.gridLayout_3.addWidget(self.nomeraster, 8, 0, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.Ok.accepted.connect(Dialog.accept) # type: ignore
        self.Ok.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelSelezionaRaster.setText(_translate("Dialog", "Lista raster"))
        self.label_2.setText(_translate("Dialog", "1. Crea un gruppo nella TOC"))
        self.lebelstep.setText(_translate("Dialog", "STEPS"))
        self.label_3.setText(_translate("Dialog", "2.  Importa i raster .tif/.tiff"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">NOTA</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Il plugin importa i gruppi</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">già presenti nella TOC di</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">QGIS.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Seleziona il gruppo di immagini </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">che vuoi visualizzare in sequenza</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Spunta il chekbox per attivare</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">il dial e ruota il dial</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "3. Seleziona il gruppo "))
        self.label_5.setText(_translate("Dialog", "4. Gira il manopolone dell\'amore"))
        self.labelseleziona.setText(_translate("Dialog", "Lista gruppi"))
        self.createGroupButton.setText(_translate("Dialog", "Create Group"))
        self.moveRasterButton.setText(_translate("Dialog", "Move Raster"))
        self.nomeraster.setText(_translate("Dialog", "Name Raster: "))
