# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpr_linker_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(786, 442)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(170, 8, 20, 411))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.labelseleziona = QtWidgets.QLabel(Dialog)
        self.labelseleziona.setGeometry(QtCore.QRect(190, 10, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelseleziona.setFont(font)
        self.labelseleziona.setObjectName("labelseleziona")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(613, 400, 161, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Ok = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.Ok.setOrientation(QtCore.Qt.Horizontal)
        self.Ok.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Ok.setObjectName("Ok")
        self.verticalLayout_3.addWidget(self.Ok)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.Sfoglia = QtWidgets.QDialogButtonBox(Dialog)
        self.Sfoglia.setGeometry(QtCore.QRect(610, 120, 75, 23))
        self.Sfoglia.setStandardButtons(QtWidgets.QDialogButtonBox.Open)
        self.Sfoglia.setCenterButtons(True)
        self.Sfoglia.setObjectName("Sfoglia")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(580, 70, 151, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(580, 90, 151, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(580, 160, 161, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(580, 180, 161, 21))
        self.label_5.setObjectName("label_5")
        self.dial = QtWidgets.QDial(Dialog)
        self.dial.setGeometry(QtCore.QRect(10, 280, 161, 141))
        self.dial.setMouseTracking(False)
        self.dial.setTabletTracking(False)
        self.dial.setAcceptDrops(False)
        self.dial.setAutoFillBackground(False)
        self.dial.setProperty("value", 0)
        self.dial.setSliderPosition(0)
        self.dial.setTracking(True)
        self.dial.setOrientation(QtCore.Qt.Horizontal)
        self.dial.setWrapping(False)
        self.dial.setNotchTarget(3.699999999999999)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.lebelstep = QtWidgets.QLabel(Dialog)
        self.lebelstep.setGeometry(QtCore.QRect(10, 40, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.lebelstep.setFont(font)
        self.lebelstep.setObjectName("lebelstep")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setEnabled(False)
        self.textBrowser.setGeometry(QtCore.QRect(10, 70, 161, 181))
        self.textBrowser.setMouseTracking(False)
        self.textBrowser.setAutoFillBackground(True)
        self.textBrowser.setFrameShape(QtWidgets.QFrame.HLine)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser.setLineWidth(-8)
        self.textBrowser.setMidLineWidth(-5)
        self.textBrowser.setObjectName("textBrowser")
        self.nomeraster = QtWidgets.QLabel(Dialog)
        self.nomeraster.setGeometry(QtCore.QRect(190, 410, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.nomeraster.setFont(font)
        self.nomeraster.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.nomeraster.setLineWidth(1)
        self.nomeraster.setMidLineWidth(0)
        self.nomeraster.setScaledContents(False)
        self.nomeraster.setObjectName("nomeraster")
        self.groupNameEdit = QtWidgets.QLineEdit(Dialog)
        self.groupNameEdit.setGeometry(QtCore.QRect(560, 260, 113, 20))
        self.groupNameEdit.setObjectName("groupNameEdit")
        self.createGroupButton = QtWidgets.QPushButton(Dialog)
        self.createGroupButton.setGeometry(QtCore.QRect(680, 260, 75, 23))
        self.createGroupButton.setObjectName("createGroupButton")
        self.moveRasterButton = QtWidgets.QPushButton(Dialog)
        self.moveRasterButton.setGeometry(QtCore.QRect(680, 230, 75, 23))
        self.moveRasterButton.setObjectName("moveRasterButton")
        self.groupListWidget = QtWidgets.QListWidget(Dialog)
        self.groupListWidget.setGeometry(QtCore.QRect(190, 40, 361, 361))
        self.groupListWidget.setObjectName("groupListWidget")
        self.dlg.openButton.clicked.connect(self.load_raster)

        self.retranslateUi(Dialog)
        self.Ok.accepted.connect(Dialog.accept) # type: ignore
        self.Ok.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelseleziona.setText(_translate("Dialog", "Selezione un gruppo"))
        self.label_2.setText(_translate("Dialog", "1. Crea un gruppo nella TOC"))
        self.label_3.setText(_translate("Dialog", "2.  Importa i raster .tif/.tiff"))
        self.label_4.setText(_translate("Dialog", "3. Seleziona il gruppo "))
        self.label_5.setText(_translate("Dialog", "4. Gira il manopolone dell\'amore"))
        self.lebelstep.setText(_translate("Dialog", "STEPS"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">NOTA</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Il plugin importa i gruppi</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">già presenti nella TOC di</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">QGIS.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Seleziona il gruppo di immagini </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">che vuoi visualizzare in sequenza</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Spunta il chekbox per attivare</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">il dial e ruota il dial</p></body></html>"))
        self.nomeraster.setText(_translate("Dialog", "Name Raster: "))
        self.createGroupButton.setText(_translate("Dialog", "Create Group"))
        self.moveRasterButton.setText(_translate("Dialog", "Move Raster"))
