# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpr_linker_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QDialog
from .gpr_linker_dialog_base import Ui_Dialog

class GPRDialog(QDialog, Ui_Dialog):
    def __init__(self, parent=None):
        super(GPRDialog, self).__init__(parent)
        self.setupUi(self)  # Imposta l'interfaccia utente
