# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GPR
                                 A QGIS plugin
 GPR
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-04-23
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Giuseppe
        email                : guarino.archeo@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


# -*- coding: utf-8 -*-
"""
GPR - QGIS Plugin Implementation
"""

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon, QStandardItemModel, QStandardItem
from qgis.PyQt.QtWidgets import QAction, QMessageBox
from qgis.core import QgsProject, QgsRasterLayer, QgsLayerTreeLayer, QgsMessageLog, Qgis
from PyQt5.QtWidgets import QWidget, QHBoxLayout, QLabel, QPushButton, QListWidgetItem


from .resources import *
from .gpr_linker_dialog import GPRDialog
import os.path


class GPR:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor."""
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.actions = []
        self.menu = self.tr(u'&GPR')
        self.first_start = None

    # Translation helper
    def tr(self, message):
        return QCoreApplication.translate('GPR', message)

    # Add actions to the toolbar/menu
    def add_action(self, icon_path, text, callback, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        self.iface.addToolBarIcon(action)
        self.iface.addPluginToMenu(self.menu, action)
        self.actions.append(action)
        return action

    def initGui(self):
        """Initialize the GUI."""
        icon_path = ':/plugins/gpr_linker/icon.png'
        self.add_action(icon_path, text=self.tr(u'GRP Linker'), callback=self.run, parent=self.iface.mainWindow())
        self.first_start = True

    def unload(self):
        """Unload the plugin."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&GPR'), action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Esegue il plugin."""
        if self.first_start:
            self.first_start = False
            self.dlg = GPRDialog()
            self.populate_group_list()

            # Collega i segnali ai metodi
            self.dlg.createGroupButton.clicked.connect(self.create_group)
            self.dlg.moveRasterButton.clicked.connect(self.move_rasters)
            self.dlg.groupListWidget.itemClicked.connect(self.on_group_selected)
            self.dlg.openButton.clicked.connect(self.load_raster)

            # Collega il dial alla funzione di aggiornamento
            self.dlg.dial.valueChanged.connect(self.update_visibility_with_dial)

        self.dlg.show()


    def add_open_button_to_group(self, group_name):
        """Aggiunge un pulsante Apri per il gruppo selezionato."""
        button = QPushButton(f"Apri {group_name}")
        button.clicked.connect(lambda: self.open_raster_file_for_group(group_name))
        # Aggiungi il pulsante al layout accanto al nome del gruppo
        layout = self.dlg.groupListWidget.layout()
        layout.addWidget(button)

    def open_raster_file(self):
        """Carica un raster nel gruppo selezionato."""
        selected_group_item = self.dlg.groupListWidget.currentItem()

        if not selected_group_item:
            QMessageBox.warning(self.dlg, "Errore", "Seleziona un gruppo prima di caricare un raster.")
            return

        group_name = selected_group_item.text()
        root = QgsProject.instance().layerTreeRoot()
        group = next((g for g in root.children() if g.name() == group_name and g.nodeType() == 0), None)

        if not group:
            QMessageBox.warning(self.dlg, "Errore", f"Il gruppo '{group_name}' non è stato trovato.")
            return

        file_paths, _ = QFileDialog.getOpenFileNames(self.dlg, "Seleziona raster", "", "Raster files (*.tif *.tiff *.png *.jpg)")
        if file_paths:
            for file_path in file_paths:
                layer_name = os.path.basename(file_path)
                raster_layer = QgsRasterLayer(file_path, layer_name)
                if raster_layer.isValid():
                    QgsProject.instance().addMapLayer(raster_layer, False)
                    layer_node = root.findLayer(raster_layer.id())
                    if layer_node:
                        cloned_node = layer_node.clone()
                        group.addChildNode(cloned_node)
                        root.removeLayer(raster_layer.id())
                    self.populate_raster_list(group_name)
                    QMessageBox.information(self.dlg, "Successo", f"Raster '{layer_name}' caricato nel gruppo '{group_name}'.")
                else:
                    QMessageBox.warning(self.dlg, "Errore", f"Il file '{layer_name}' non è un raster valido.")

    def populate_group_list(self):
        """Popola la lista dei gruppi nella GUI."""
        try:
            root = QgsProject.instance().layerTreeRoot()
            self.dlg.groupListWidget.clear()
            groups = [node.name() for node in root.children() if node.nodeType() == 0]

            if groups:
                self.dlg.groupListWidget.addItems(groups)
            else:
                QMessageBox.warning(self.dlg, "Attenzione", "Non ci sono gruppi nella TOC.")
        except Exception as e:
            QMessageBox.critical(self.dlg, "Errore", f"Errore durante il popolamento dei gruppi: {str(e)}")

    def populate_raster_list(self, group_name=None):
        """Popola la lista dei raster in base al gruppo selezionato."""
        try:
            self.dlg.rasterListWidget.clear()

            if group_name:
                root = QgsProject.instance().layerTreeRoot()
                group = next((g for g in root.children() if g.name() == group_name and g.nodeType() == 0), None)

                if group:
                    rasters = [
                        child.layer().name()
                        for child in group.children()
                        if isinstance(child, QgsLayerTreeLayer) and isinstance(child.layer(), QgsRasterLayer)
                    ]
                    self.dlg.rasterListWidget.addItems(rasters)
                else:
                    QMessageBox.warning(self.dlg, "Errore", f"Gruppo '{group_name}' non trovato.")
            else:
                QMessageBox.information(self.dlg, "Informazione", "Seleziona un gruppo per vedere i raster.")
        except Exception as e:
            QMessageBox.critical(self.dlg, "Errore", f"Errore durante il popolamento dei raster: {str(e)}")

    def on_group_selected(self, item):
        """Gestisce la selezione di un gruppo nella GUI."""
        if item:
            group_name = item.text()
            self.populate_raster_list(group_name)
        else:
            QMessageBox.warning(self.dlg, "Errore", "Seleziona un gruppo valido.")

    def update_visibility_with_dial(self, value):
        """Aggiorna la visibilità dei raster nei gruppi selezionati in base al valore del dial."""
        # Ottieni tutti i gruppi selezionati
        selected_group_items = self.dlg.groupListWidget.selectedItems()
        if not selected_group_items:
            QMessageBox.warning(self.dlg, "Errore", "Seleziona almeno un gruppo prima di usare il dial.")
            return

        root = QgsProject.instance().layerTreeRoot()

        # Itera attraverso i gruppi selezionati
        for group_item in selected_group_items:
            group_name = group_item.text()
            print(f"Gruppo selezionato: {group_name}")

            # Trova il gruppo nella TOC
            group = next((g for g in root.children() if g.name() == group_name and g.nodeType() == 0), None)
            if not group:
                QMessageBox.critical(self.dlg, "Errore", f"Gruppo '{group_name}' non trovato.")
                continue

            # Ottieni i raster nel gruppo
            raster_nodes = [
                child for child in group.children()
                if isinstance(child, QgsLayerTreeLayer) and isinstance(child.layer(), QgsRasterLayer)
            ]

            if not raster_nodes:
                QMessageBox.warning(self.dlg, "Errore", f"Il gruppo '{group_name}' non contiene raster.")
                continue

            # Determina il raster da rendere visibile
            index = value % len(raster_nodes)
            print(f"Impostando visibile il raster all'indice {index} nel gruppo '{group_name}'")

            # Aggiorna la visibilità dei raster nel gruppo
            for i, node in enumerate(raster_nodes):
                node.setItemVisibilityChecked(i == index)

            # Aggiorna il nome del raster visibile nella GUI
            visible_raster_name = raster_nodes[index].layer().name()
            print(f"Raster visibile nel gruppo '{group_name}': {visible_raster_name}")

    def create_group(self):
        """Crea un nuovo gruppo e aggiorna la lista dei gruppi."""
        group_name = self.dlg.groupNameEdit.text().strip()
        if not group_name:
            QMessageBox.warning(self.dlg, "Errore", "Il nome del gruppo non può essere vuoto.")
            return

        root = QgsProject.instance().layerTreeRoot()

        # Verifica che il gruppo non esista già
        if any(group.name() == group_name for group in root.children() if group.nodeType() == 0):
            QMessageBox.warning(self.dlg, "Errore", f"Il gruppo '{group_name}' esiste già.")
            return

        # Crea il gruppo
        root.addGroup(group_name)

        # Aggiungi il gruppo alla lista
        self.add_group_with_button(group_name)

        QMessageBox.information(self.dlg, "Successo", f"Gruppo '{group_name}' creato.")

    def add_group_with_button(self, group_name):
        """Aggiunge il gruppo alla lista dei gruppi."""
        # Controlla se il gruppo è già presente nella lista
        for i in range(self.dlg.groupListWidget.count()):
            if self.dlg.groupListWidget.item(i).text() == group_name:
                QMessageBox.information(self.dlg, "Informazione", f"Il gruppo '{group_name}' è già presente nella lista.")
                return

        # Aggiungi il nome del gruppo come elemento alla lista
        self.dlg.groupListWidget.addItem(group_name)


    def load_raster(self):
        """Apre un dialogo per selezionare e caricare più raster in un gruppo selezionato."""
        try:
            # Controlla se un gruppo è selezionato
            selected_group_item = self.dlg.groupListWidget.currentItem()
            if not selected_group_item:
                QMessageBox.warning(self.dlg, "Errore", "Seleziona un gruppo prima di caricare i raster.")
                return

            group_name = selected_group_item.text()
            print(f"Gruppo selezionato: {group_name}")

            # Apre il file dialog per selezionare più file
            file_paths, _ = QFileDialog.getOpenFileNames(
                self.dlg, "Seleziona i raster", "", "Raster files (*.tif *.tiff *.png *.jpg *.img)"
            )
            if not file_paths:
                QMessageBox.warning(self.dlg, "Errore", "Nessun file selezionato.")
                return

            # Trova il gruppo
            root = QgsProject.instance().layerTreeRoot()
            group = next((g for g in root.children() if g.name() == group_name and g.nodeType() == 0), None)
            if not group:
                QMessageBox.critical(self.dlg, "Errore", f"Il gruppo '{group_name}' non è stato trovato.")
                return

            print(f"Gruppo '{group_name}' trovato.")

            # Carica e aggiungi ciascun raster selezionato
            for file_path in file_paths:
                layer_name = os.path.basename(file_path)
                raster_layer = QgsRasterLayer(file_path, layer_name)

                if not raster_layer.isValid():
                    QMessageBox.warning(self.dlg, "Errore", f"Il file '{layer_name}' non è un raster valido.")
                    continue

                QgsProject.instance().addMapLayer(raster_layer, False)
                print(f"Raster '{layer_name}' aggiunto al progetto con ID: {raster_layer.id()}")

                # Crea manualmente il nodo per il layer e aggiungilo al gruppo
                cloned_node = QgsLayerTreeLayer(raster_layer)
                group.addChildNode(cloned_node)

            # Aggiorna la lista dei raster
            self.populate_raster_list(group_name)
            QMessageBox.information(self.dlg, "Successo", "Raster aggiunti al gruppo selezionato.")

        except Exception as e:
            QMessageBox.critical(self.dlg, "Errore", f"Si è verificato un errore imprevisto: {str(e)}")
            print(f"Errore: {str(e)}")


    def get_selected_group(self):
        """Restituisce il nome del gruppo selezionato."""
        selected_group_item = self.dlg.groupListWidget.currentItem()
        if not selected_group_item:
            QMessageBox.warning(self.dlg, "Errore", "Seleziona un gruppo prima di caricare un raster.")
            return None
        return selected_group_item.text()

    def open_file_dialog(self):
        """Apre un dialogo per selezionare un file raster."""
        file_path, _ = QFileDialog.getOpenFileName(
            self.dlg, "Seleziona un raster", "", "Raster files (*.tif *.tiff *.png *.jpg *.img)"
        )
        if not file_path:
            QMessageBox.warning(self.dlg, "Errore", "Nessun file selezionato.")
            return None
        return file_path

    def create_raster_layer(self, file_path):
        """Crea un QgsRasterLayer dal file selezionato."""
        layer_name = os.path.basename(file_path)
        raster_layer = QgsRasterLayer(file_path, layer_name)
        if not raster_layer.isValid():
            QMessageBox.critical(self.dlg, "Errore", f"Il file '{layer_name}' non è un raster valido.")
            return None
        QgsProject.instance().addMapLayer(raster_layer, False)
        return raster_layer

    def add_layer_to_group(self, raster_layer, group_name):
        """Aggiunge un raster a un gruppo specifico."""
        root = QgsProject.instance().layerTreeRoot()
        group = next((g for g in root.children() if g.name() == group_name and g.nodeType() == 0), None)
        if not group:
            QMessageBox.critical(self.dlg, "Errore", f"Il gruppo '{group_name}' non è stato trovato.")
            return

        layer_node = root.findLayer(raster_layer.id())
        if not layer_node:
            QMessageBox.critical(self.dlg, "Errore", f"Impossibile trovare il nodo per il raster '{raster_layer.name()}'.")
            return

        cloned_node = layer_node.clone()
        group.addChildNode(cloned_node)
        root.removeLayer(raster_layer.id())
        self.populate_raster_list(group_name)
        QMessageBox.information(self.dlg, "Successo", f"Raster '{raster_layer.name()}' aggiunto al gruppo '{group_name}'.")

    def move_rasters(self):
        """Sposta il raster selezionato in un altro gruppo."""
        selected_raster_item = self.dlg.rasterListWidget.currentItem()
        selected_group_item = self.dlg.groupListWidget.currentItem()

        if not selected_raster_item or not selected_group_item:
            QMessageBox.warning(self.dlg, "Errore", "Seleziona sia un raster che un gruppo.")
            return

        raster_name = selected_raster_item.text()
        target_group_name = selected_group_item.text()

        root = QgsProject.instance().layerTreeRoot()
        target_group = next((g for g in root.children() if g.name() == target_group_name and g.nodeType() == 0), None)

        if not target_group:
            QMessageBox.warning(self.dlg, "Errore", f"Gruppo '{target_group_name}' non trovato.")
            return

        layer = next((l for l in QgsProject.instance().mapLayers().values() if l.name() == raster_name), None)
        if layer:
            layer_node = root.findLayer(layer.id())
            if layer_node:
                cloned_node = layer_node.clone()
                target_group.addChildNode(cloned_node)
                root.removeLayer(layer.id())
                self.populate_raster_list(target_group_name)
                QMessageBox.information(self.dlg, "Successo", f"Raster '{raster_name}' spostato nel gruppo '{target_group_name}'.")
        else:
            QMessageBox.warning(self.dlg, "Errore", f"Raster '{raster_name}' non trovato.")
