# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GPRDialog
                                 A QGIS plugin
 GPR
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-23
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Giuseppe
        email                : guarino.archeo@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.core import QgsProject, QgsRasterLayer, QgsLayerTreeGroup, QgsLayerTreeLayer
from qgis.PyQt import QtWidgets, uic
from PyQt5.QtGui import QStandardItem, QStandardItemModel
from qgis.PyQt.QtWidgets import QInputDialog, QFileDialog


# Questo carica il file .ui in modo che PyQt possa popolare il plugin con gli elementi dal Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'gpr_linker_dialog_base.ui'))


class GPRDialog(QtWidgets.QDialog, FORM_CLASS):
    
    def __init__(self, parent=None):
        """Constructor."""
        super(GPRDialog, self).__init__(parent)
       
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect

        self.setupUi(self)

        # Initialize the standard item model for the list view
        self.list_model = QStandardItemModel()
        self.listView.setModel(self.list_model)  # Set the model for the list view
        
        # Connect the "Sfoglia" button
        self.Sfoglia.clicked.connect(self.browse_rasters)

        # Find the dial in the dialog layout
        self.dial = self.findChild(QtWidgets.QDial, "dial")
        self.dial.setEnabled(False)  # Disable the dial initially

        # Connect the valueChanged signal of the dial to the toggle_raster_visibility method
        self.dial.valueChanged.connect(self.toggle_raster_visibility)

    def populate_group_checkbox_list(self):
        #Populate the QListView with checkboxes for each group in the TOC.
        root = QgsProject.instance().layerTreeRoot()
        self.list_model.clear()  # Clear the model

        for child in root.children():
            if isinstance(child, QgsLayerTreeGroup):
                item = QStandardItem(child.name())
                item.setCheckable(True)  # Make the item checkable
                self.list_model.appendRow(item)

    def browse_rasters(self):
        # Open the file dialog to select raster files.
        files, _ = QFileDialog.getOpenFileNames(self, "Select raster files", "/", "Raster files (*.tif *.tiff *.png *.jpg)")
        if files:
            print("Selected raster files:", files)
            # Open a dialog to input the group name
            group_name, ok = QInputDialog.getText(self, "Enter Group Name", "Group Name:")
            if ok:
                # Call load_rasters_into_group after importing the raster files
                self.load_rasters_into_group(files, group_name)
                # Update the group list after loading the raster files
                self.populate_group_checkbox_list()
                # Set the range of the dial based on the number of raster layers in the group
                self.update_dial_range()

        # Funzione per caricare i raster in un gruppo specificato
    
    def load_rasters_into_group(self, raster_files, group_name):
        # Load raster files into the specified group.
        group = QgsProject.instance().layerTreeRoot().findGroup(group_name)

        if not group:
            # If the group doesn't exist, create it
            group = QgsLayerTreeGroup(group_name)
            QgsProject.instance().layerTreeRoot().addChildNode(group)

        for file in raster_files:
            layer = QgsRasterLayer(file, os.path.basename(file))
            if layer.isValid():
                QgsProject.instance().addMapLayer(layer, False) #Questa stringa inserisce i raster direttamente nella TOC
                layer_node = QgsLayerTreeLayer(layer)
                group.insertChildNode(0, QgsLayerTreeLayer(layer))
            else:
                print(f"Unable to load raster file: {file}")

    def populate_group_list(self):
        #Populate the QListView with items for each group in the TOC.
        model = QtWidgets.QStandardItemModel()
        root = QgsProject.instance().layerTreeRoot()

        for child in root.children():
            if isinstance(child, QgsLayerTreeGroup):
                item = QtWidgets.QStandardItem(child.name())
                model.appendRow(item)

        self.listView.setModel(model)

    # Funzione per alternare la visibilità dei raster all'interno del gruppo
    def toggle_raster_visibility(value):
        # Get the selected group from the list view
        selected_index = self.listView.selectedIndexes()
        if not selected_index:
            print("Nessun gruppo selezionato.")
            return

        group_name = selected_index[0].data()
        group = QgsProject.instance().layerTreeRoot().findGroup(group_name)
        if not group:
            print(f"Nessun gruppo trovato con il nome: {group_name}")
            return

        # Get the layer nodes (not the layers themselves) in the group
        layer_nodes = [child for child in group.children() if isinstance(child, QgsLayerTreeLayer)]
        if not layer_nodes:
            print("Nessun raster layers nel gruppo selezionato.")
            return

        # Adjust the value to loop around if it exceeds the layer nodes length
        num_layers = len(layer_nodes)
        adjusted_value = value % num_layers

        # Disable the previous raster
        previous_index = adjusted_value - 1 if adjusted_value > 0 else num_layers - 1
        previous_layer_node = layer_nodes[previous_index]
        previous_layer_node.setItemVisibilityChecked(False)

        # Enable the current raster
        current_layer_node = layer_nodes[adjusted_value]
        current_layer_node.setItemVisibilityChecked(True)


        # Funzione per aggiornare la visibilità del layer
        def update_layer_visibility(value):
            for node in layer_nodes:
                node.setItemVisibilityChecked(False)
            layer_nodes[value].setItemVisibilityChecked(True)

        dial.valueChanged.connect(update_layer_visibility)
        layout.addWidget(dial)

        dialog.exec_()

    def update_dial_range(self):
        #Update the range of the dial based on the number of raster layers in the selected group.
        selected_index = self.listView.selectedIndexes()
        if selected_index:
            group_name = selected_index[0].data()
            group = QgsProject.instance().layerTreeRoot().findGroup(group_name)
            if group:
                layer_nodes = [child for child in group.children() if isinstance(child, QgsLayerTreeLayer)]
                if layer_nodes:
                    self.dial.setRange(0, len(layer_nodes) - 1)
                else:
                    print("No raster layers in the selected group.")
            else:
                print(f"No group found with name: {group_name}")
        else:
            print("No group selected.")
