"""CSV -> GeoTIFF slice generator with IDW interpolation.

Supports:
  - single-band (any numeric field)
  - 3-band RGB (value_field='rgb')

Input modes:
  - z_field set: Z is read from CSV rows and slices are generated by z_step
  - z_field None: each CSV file is treated as one depth slice using depth_by_file
"""

from __future__ import annotations

import csv
import json
import os
import re
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np

from .gpr_las_slicer import (
    _bin_with_idw,
    _write_qml_multiband,
    _write_tif_rgb,
    _write_tif_singleband,
)


SIDECAR_FILENAME = ".csv_slicer_params.json"

CSV_SEPARATOR_MODES = [
    ("auto", "Auto detect (, ; tab spazio)"),
    ("comma", "Comma (,)"),
    ("semicolon", "Semicolon (;)"),
    ("tab", "Tab"),
    ("space", "Space"),
    ("comma_tab", "Comma + Tab"),
    ("comma_space", "Comma + Space"),
    ("tab_space", "Tab + Space"),
    ("common_mixed", "Comma + Semicolon + Tab + Space"),
]


def csv_separator_mode_choices() -> List[Tuple[str, str]]:
    return list(CSV_SEPARATOR_MODES)


def normalize_csv_separator_mode(mode: Optional[str]) -> str:
    key = str(mode or "auto").strip().lower()
    valid = {k for k, _ in CSV_SEPARATOR_MODES}
    return key if key in valid else "auto"


def csv_separator_mode_label(mode: Optional[str]) -> str:
    key = normalize_csv_separator_mode(mode)
    for k, label in CSV_SEPARATOR_MODES:
        if k == key:
            return label
    return "Auto detect (, ; tab spazio)"


def save_csv_slicer_params(output_dir: str, params: dict) -> str:
    path = os.path.join(output_dir, SIDECAR_FILENAME)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(params, f, indent=2, ensure_ascii=True)
    return path


def load_csv_slicer_params(output_dir: str) -> Optional[dict]:
    path = os.path.join(output_dir, SIDECAR_FILENAME)
    if not os.path.isfile(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None


def _safe_float(value) -> Optional[float]:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    # Handle EU decimal comma and thousands separators conservatively.
    text = text.replace(" ", "")
    if "," in text and "." in text:
        if text.rfind(",") > text.rfind("."):
            text = text.replace(".", "").replace(",", ".")
        else:
            text = text.replace(",", "")
    else:
        text = text.replace(",", ".")
    try:
        return float(text)
    except Exception:
        return None


def _sniff_dialect(sample: str) -> csv.Dialect:
    try:
        return csv.Sniffer().sniff(sample, delimiters=",;\t| ")
    except Exception:
        class _Fallback(csv.Dialect):
            delimiter = ";" if sample.count(";") > sample.count(",") else ","
            quotechar = '"'
            escapechar = None
            doublequote = True
            skipinitialspace = True
            lineterminator = "\n"
            quoting = csv.QUOTE_MINIMAL

        return _Fallback()


def _parser_from_separator_mode(sample: str, separator_mode: str) -> dict:
    mode = normalize_csv_separator_mode(separator_mode)
    single = {
        "comma": ",",
        "semicolon": ";",
        "tab": "\t",
        "space": " ",
    }
    regex = {
        "comma_tab": r"[,\t]+",
        "comma_space": r"[, ]+",
        "tab_space": r"[\t ]+",
        "common_mixed": r"[,;\t ]+",
    }
    if mode == "auto":
        return {
            "kind": "csv",
            "dialect": _sniff_dialect(sample),
            "separator_mode": mode,
        }
    if mode in single:
        return {
            "kind": "csv",
            "delimiter": single[mode],
            "separator_mode": mode,
        }
    if mode in regex:
        return {
            "kind": "regex",
            "pattern": regex[mode],
            "separator_mode": mode,
        }
    return {
        "kind": "csv",
        "dialect": _sniff_dialect(sample),
        "separator_mode": "auto",
    }


def _split_line_regex(line: str, pattern: str) -> List[str]:
    parts = re.split(pattern, str(line or "").strip())
    cleaned = []
    for token in parts:
        t = str(token or "").strip()
        if len(t) >= 2 and ((t.startswith('"') and t.endswith('"')) or (t.startswith("'") and t.endswith("'"))):
            t = t[1:-1]
        cleaned.append(t)
    return cleaned


def _read_headers(path: str, encoding: str, parser: dict) -> List[str]:
    if parser.get("kind") == "regex":
        pattern = str(parser.get("pattern") or r"[,;\t ]+")
        with open(path, "r", encoding=encoding, newline="") as f:
            for raw in f:
                line = str(raw or "").strip()
                if not line:
                    continue
                headers = [h for h in _split_line_regex(line, pattern) if str(h).strip()]
                return [str(h).strip() for h in headers]
        return []

    dialect = parser.get("dialect")
    delimiter = parser.get("delimiter")
    with open(path, "r", encoding=encoding, newline="") as f:
        if dialect is not None:
            reader = csv.reader(f, dialect=dialect)
        elif delimiter is not None:
            reader = csv.reader(f, delimiter=str(delimiter))
        else:
            reader = csv.reader(f)
        for row in reader:
            headers = [str(h or "").strip() for h in row if str(h or "").strip()]
            if headers:
                return headers
    return []


def _detect_csv_format(path: str, separator_mode: str = "auto") -> Tuple[str, dict, List[str]]:
    last_error = None
    for encoding in ("utf-8-sig", "utf-8", "cp1252", "latin-1"):
        try:
            with open(path, "r", encoding=encoding, newline="") as f:
                sample = f.read(8192)
            parser = _parser_from_separator_mode(sample, separator_mode)
            headers = _read_headers(path, encoding, parser)
            if headers:
                return encoding, parser, headers
            last_error = RuntimeError("No headers found")
        except Exception as e:
            last_error = e
            continue
    if last_error is None:
        last_error = RuntimeError("Unknown CSV format error")
    raise RuntimeError(f"Unable to read CSV headers from '{path}': {last_error}")


def _iter_dict_rows(path: str, encoding: str, parser: dict) -> Iterable[dict]:
    if parser.get("kind") == "regex":
        pattern = str(parser.get("pattern") or r"[,;\t ]+")
        headers = None
        with open(path, "r", encoding=encoding, newline="") as f:
            for raw in f:
                line = str(raw or "").strip()
                if not line:
                    continue
                parts = _split_line_regex(line, pattern)
                if headers is None:
                    headers = [str(h or "").strip() for h in parts]
                    continue
                if not headers:
                    continue
                vals = list(parts)
                if len(vals) < len(headers):
                    vals.extend([""] * (len(headers) - len(vals)))
                elif len(vals) > len(headers):
                    vals = vals[: len(headers)]
                yield dict(zip(headers, vals))
        return

    dialect = parser.get("dialect")
    delimiter = parser.get("delimiter")
    with open(path, "r", encoding=encoding, newline="") as f:
        if dialect is not None:
            reader = csv.DictReader(f, dialect=dialect)
        elif delimiter is not None:
            reader = csv.DictReader(f, delimiter=str(delimiter))
        else:
            reader = csv.DictReader(f)
        for row in reader:
            if row is None:
                continue
            yield row


def _suggest_field(field_names: List[str], candidates: List[str]) -> str:
    lowered = {name.lower(): name for name in field_names}
    for cand in candidates:
        exact = lowered.get(cand.lower())
        if exact:
            return exact
    for cand in candidates:
        c = cand.lower()
        for name in field_names:
            if c in name.lower():
                return name
    return field_names[0] if field_names else ""


def diagnose_csv_fields_detailed(
    csv_paths: List[str],
    n_preview: int = 6,
    n_sample_rows: int = 30000,
    separator_mode: str = "auto",
) -> dict:
    result = {
        "rows": [],
        "all_field_names": [],
        "shared_field_names": [],
        "suggested_x": "",
        "suggested_y": "",
        "suggested_z": "",
        "suggested_r": "",
        "suggested_g": "",
        "suggested_b": "",
        "suggested_single": "",
        "n_files": len(csv_paths or []),
        "n_points_sampled": 0,
        "recognized_complete": False,
    }
    paths = list(csv_paths or [])
    if not paths:
        return result

    # Build field intersection across selected files.
    header_sets = []
    first_headers = []
    for idx, path in enumerate(paths):
        try:
            _, _, headers = _detect_csv_format(path, separator_mode=separator_mode)
        except Exception:
            headers = []
        header_sets.append(set(headers))
        if idx == 0:
            first_headers = list(headers)

    if header_sets:
        shared = set.intersection(*header_sets) if len(header_sets) > 1 else set(header_sets[0])
        shared_ordered = [h for h in first_headers if h in shared]
    else:
        shared_ordered = list(first_headers)

    all_fields = shared_ordered or first_headers
    result["all_field_names"] = list(all_fields)
    result["shared_field_names"] = list(shared_ordered)
    if not all_fields:
        return result

    # Column preview/stats from first CSV.
    try:
        enc0, parser0, _ = _detect_csv_format(paths[0], separator_mode=separator_mode)
    except Exception:
        return result

    previews = {name: [] for name in all_fields}
    min_v = {name: None for name in all_fields}
    max_v = {name: None for name in all_fields}
    numeric_counts = {name: 0 for name in all_fields}
    sampled = 0

    for row in _iter_dict_rows(paths[0], enc0, parser0):
        sampled += 1
        for name in all_fields:
            raw = row.get(name, "")
            text = str(raw or "").strip()
            if text and len(previews[name]) < n_preview:
                previews[name].append(text)
            val = _safe_float(raw)
            if val is None:
                continue
            numeric_counts[name] += 1
            if min_v[name] is None or val < min_v[name]:
                min_v[name] = val
            if max_v[name] is None or val > max_v[name]:
                max_v[name] = val
        if sampled >= int(n_sample_rows):
            break

    result["n_points_sampled"] = sampled
    rows = []
    for name in all_fields:
        mn = min_v[name]
        mx = max_v[name]
        rows.append(
            {
                "name": name,
                "values": previews[name],
                "min": float(mn) if mn is not None else 0.0,
                "max": float(mx) if mx is not None else 0.0,
                "has_data": numeric_counts[name] > 0 and (mn is not None) and (mx is not None),
            }
        )
    result["rows"] = rows

    result["suggested_x"] = _suggest_field(
        all_fields, ["x", "coord_x", "easting", "east", "lon", "longitude"]
    )
    result["suggested_y"] = _suggest_field(
        all_fields, ["y", "coord_y", "northing", "north", "lat", "latitude"]
    )
    result["suggested_z"] = _suggest_field(
        all_fields, ["z", "coord_z", "depth", "elevation", "elev", "quota"]
    )
    result["suggested_r"] = _suggest_field(all_fields, ["r", "red"])
    result["suggested_g"] = _suggest_field(all_fields, ["g", "green"])
    result["suggested_b"] = _suggest_field(all_fields, ["b", "blue"])
    result["suggested_single"] = _suggest_field(
        all_fields, ["intensity", "i", "value", "amplitude", "reflectance", "signal"]
    )

    has_xy = bool(result["suggested_x"]) and bool(result["suggested_y"])
    has_z = bool(result["suggested_z"])
    has_single = bool(result["suggested_single"])
    has_rgb = bool(result["suggested_r"]) and bool(result["suggested_g"]) and bool(result["suggested_b"])
    result["recognized_complete"] = bool(has_xy and has_z and (has_single or has_rgb))
    return result


def _to_numpy(values: List[float]) -> np.ndarray:
    return np.asarray(values, dtype=np.float64)


def _slice_arrays_to_tifs(
    x: np.ndarray,
    y: np.ndarray,
    z: np.ndarray,
    output_dir: str,
    resolution: float,
    z_step: float,
    z_min: Optional[float],
    z_max: Optional[float],
    radius: Optional[float],
    epsg: Optional[int],
    value_field: str,
    single_values: Optional[np.ndarray] = None,
    r_values: Optional[np.ndarray] = None,
    g_values: Optional[np.ndarray] = None,
    b_values: Optional[np.ndarray] = None,
    idw_power: float = 2.0,
    min_points: int = 1,
) -> List[dict]:
    if radius is None:
        radius = float(resolution) * (2 ** 0.5)
    os.makedirs(output_dir, exist_ok=True)
    use_rgb = value_field == "rgb"

    if x.size == 0 or y.size == 0 or z.size == 0:
        return []

    if z_min is None:
        z_min = float(np.nanmin(z))
    if z_max is None:
        z_max = float(np.nanmax(z))
    if z_max < z_min:
        return []

    x_min = float(np.nanmin(x))
    y_min = float(np.nanmin(y))
    x_max = float(np.nanmax(x))
    y_max = float(np.nanmax(y))
    if x_max <= x_min or y_max <= y_min:
        return []

    n_x = len(np.arange(x_min, x_max + resolution * 0.5, resolution))
    n_y = len(np.arange(y_min, y_max + resolution * 0.5, resolution))
    kw = dict(
        x_min=x_min,
        y_min=y_min,
        n_x=n_x,
        n_y=n_y,
        resolution=resolution,
        radius=radius,
        power=idw_power,
        min_points=min_points,
    )

    z_levels = np.arange(float(z_min), float(z_max) + float(z_step) * 0.5, float(z_step))
    results = []
    for iz, z_lev in enumerate(z_levels):
        z_from = float(z_lev - z_step / 2.0)
        z_to = float(z_lev + z_step / 2.0)
        mask = (z >= z_from) & (z < z_to)
        if not np.any(mask):
            continue

        z_label = f"{z_lev:.4f}".replace(".", "_").replace("-", "m")
        tif_name = f"slice_{iz:04d}_z{z_label}.tif"
        tif_path = os.path.join(output_dir, tif_name)

        if use_rgb:
            if r_values is None or g_values is None or b_values is None:
                raise RuntimeError("RGB values are missing for value_field='rgb'.")

            def _ch(ch_arr):
                return _bin_with_idw(x[mask], y[mask], ch_arr[mask], **kw)

            r_grid = _ch(r_values)
            g_grid = _ch(g_values)
            b_grid = _ch(b_values)
            ranges = _write_tif_rgb(
                r_grid,
                g_grid,
                b_grid,
                tif_path,
                x_min,
                y_min,
                y_max,
                resolution,
                epsg,
            )
            _write_qml_multiband(tif_path, *ranges)
        else:
            if single_values is None:
                raise RuntimeError("Single values are missing for single-band slicing.")
            grid = _bin_with_idw(x[mask], y[mask], single_values[mask], **kw)
            _write_tif_singleband(grid, tif_path, x_min, y_min, y_max, resolution, epsg)

        results.append(
            {
                "path": tif_path,
                "z_from": round(z_from, 6),
                "z_to": round(z_to, 6),
                "z_center": round(float(z_lev), 6),
                "index": iz,
                "name": os.path.splitext(tif_name)[0],
            }
        )
    return results


def _collect_points_for_mode(
    csv_paths: List[str],
    x_field: str,
    y_field: str,
    z_field: Optional[str],
    value_field: str,
    single_field: str,
    r_field: str,
    g_field: str,
    b_field: str,
    depth_by_file: Optional[Dict[str, float]],
    separator_mode: str = "auto",
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    x_vals: List[float] = []
    y_vals: List[float] = []
    z_vals: List[float] = []
    single_vals: List[float] = []
    r_vals: List[float] = []
    g_vals: List[float] = []
    b_vals: List[float] = []

    for path in csv_paths:
        enc, parser, headers = _detect_csv_format(path, separator_mode=separator_mode)
        req = [x_field, y_field]
        if z_field:
            req.append(z_field)
        if value_field == "rgb":
            req.extend([r_field, g_field, b_field])
        else:
            req.append(single_field)

        missing = [name for name in req if name and name not in headers]
        if missing:
            raise RuntimeError(f"CSV '{os.path.basename(path)}' missing columns: {', '.join(missing)}")

        file_depth = None
        if not z_field:
            if depth_by_file is None or path not in depth_by_file:
                raise RuntimeError(f"No depth assigned for CSV '{os.path.basename(path)}'.")
            file_depth = float(depth_by_file[path])

        for row in _iter_dict_rows(path, enc, parser):
            xv = _safe_float(row.get(x_field))
            yv = _safe_float(row.get(y_field))
            if xv is None or yv is None:
                continue

            if z_field:
                zv = _safe_float(row.get(z_field))
                if zv is None:
                    continue
            else:
                zv = float(file_depth)

            if value_field == "rgb":
                rv = _safe_float(row.get(r_field))
                gv = _safe_float(row.get(g_field))
                bv = _safe_float(row.get(b_field))
                if rv is None:
                    rv = 0.0
                if gv is None:
                    gv = 0.0
                if bv is None:
                    bv = 0.0
                r_vals.append(rv)
                g_vals.append(gv)
                b_vals.append(bv)
            else:
                sv = _safe_float(row.get(single_field))
                if sv is None:
                    sv = 0.0
                single_vals.append(sv)

            x_vals.append(xv)
            y_vals.append(yv)
            z_vals.append(zv)

    x_arr = _to_numpy(x_vals)
    y_arr = _to_numpy(y_vals)
    z_arr = _to_numpy(z_vals)
    s_arr = _to_numpy(single_vals) if single_vals else np.asarray([], dtype=np.float64)
    r_arr = _to_numpy(r_vals) if r_vals else np.asarray([], dtype=np.float64)
    g_arr = _to_numpy(g_vals) if g_vals else np.asarray([], dtype=np.float64)
    b_arr = _to_numpy(b_vals) if b_vals else np.asarray([], dtype=np.float64)
    return x_arr, y_arr, z_arr, s_arr, r_arr, g_arr, b_arr


def slice_csv_to_tifs(
    csv_paths: List[str],
    output_dir: str,
    resolution: float = 0.10,
    z_step: float = 0.05,
    z_min: Optional[float] = None,
    z_max: Optional[float] = None,
    radius: Optional[float] = None,
    epsg: Optional[int] = None,
    x_field: str = "x",
    y_field: str = "y",
    z_field: Optional[str] = "z",
    value_field: str = "intensity",
    single_field: str = "intensity",
    r_field: str = "red",
    g_field: str = "green",
    b_field: str = "blue",
    depth_by_file: Optional[Dict[str, float]] = None,
    separator_mode: str = "auto",
    idw_power: float = 2.0,
    min_points: int = 1,
) -> List[dict]:
    paths = [p for p in (csv_paths or []) if p and os.path.exists(p)]
    if not paths:
        return []

    if z_field is None:
        # One slice per file-depth in selection order.
        if depth_by_file is None:
            return []
        results = []
        running_idx = 0
        if radius is None:
            radius = float(resolution) * (2 ** 0.5)
        os.makedirs(output_dir, exist_ok=True)
        use_rgb = value_field == "rgb"
        for path in paths:
            depth = float(depth_by_file.get(path, 0.0))
            px, py, pz, ps, pr, pg, pb = _collect_points_for_mode(
                csv_paths=[path],
                x_field=x_field,
                y_field=y_field,
                z_field=None,
                value_field=value_field,
                single_field=single_field,
                r_field=r_field,
                g_field=g_field,
                b_field=b_field,
                depth_by_file={path: depth},
                separator_mode=separator_mode,
            )
            if px.size == 0:
                continue
            x_min = float(np.nanmin(px))
            y_min = float(np.nanmin(py))
            x_max = float(np.nanmax(px))
            y_max = float(np.nanmax(py))
            if x_max <= x_min or y_max <= y_min:
                continue
            n_x = len(np.arange(x_min, x_max + resolution * 0.5, resolution))
            n_y = len(np.arange(y_min, y_max + resolution * 0.5, resolution))
            kw = dict(
                x_min=x_min,
                y_min=y_min,
                n_x=n_x,
                n_y=n_y,
                resolution=resolution,
                radius=radius,
                power=idw_power,
                min_points=min_points,
            )

            base = os.path.splitext(os.path.basename(path))[0]
            depth_label = f"{depth:.4f}".replace(".", "_").replace("-", "m")
            tif_name = f"slice_{running_idx:04d}_{base}_z{depth_label}.tif"
            tif_path = os.path.join(output_dir, tif_name)

            if use_rgb:
                if pr.size == 0 or pg.size == 0 or pb.size == 0:
                    continue
                r_grid = _bin_with_idw(px, py, pr, **kw)
                g_grid = _bin_with_idw(px, py, pg, **kw)
                b_grid = _bin_with_idw(px, py, pb, **kw)
                ranges = _write_tif_rgb(
                    r_grid,
                    g_grid,
                    b_grid,
                    tif_path,
                    x_min,
                    y_min,
                    y_max,
                    resolution,
                    epsg,
                )
                _write_qml_multiband(tif_path, *ranges)
            else:
                if ps.size == 0:
                    continue
                grid = _bin_with_idw(px, py, ps, **kw)
                _write_tif_singleband(grid, tif_path, x_min, y_min, y_max, resolution, epsg)

            z_from = float(depth - z_step / 2.0)
            z_to = float(depth + z_step / 2.0)
            results.append(
                {
                    "path": tif_path,
                    "z_from": round(z_from, 6),
                    "z_to": round(z_to, 6),
                    "z_center": round(depth, 6),
                    "index": running_idx,
                    "name": os.path.splitext(tif_name)[0],
                }
            )
            running_idx += 1
        return results

    x_arr, y_arr, z_arr, s_arr, r_arr, g_arr, b_arr = _collect_points_for_mode(
        csv_paths=paths,
        x_field=x_field,
        y_field=y_field,
        z_field=z_field,
        value_field=value_field,
        single_field=single_field,
        r_field=r_field,
        g_field=g_field,
        b_field=b_field,
        depth_by_file=depth_by_file,
        separator_mode=separator_mode,
    )

    return _slice_arrays_to_tifs(
        x=x_arr,
        y=y_arr,
        z=z_arr,
        output_dir=output_dir,
        resolution=resolution,
        z_step=z_step,
        z_min=z_min,
        z_max=z_max,
        radius=radius,
        epsg=epsg,
        value_field=value_field,
        single_values=s_arr if s_arr.size else None,
        r_values=r_arr if r_arr.size else None,
        g_values=g_arr if g_arr.size else None,
        b_values=b_arr if b_arr.size else None,
        idw_power=idw_power,
        min_points=min_points,
    )
